### ISSUE TITLE
issue with the battery just showing N/A

### ISSUE THREAD

**Issue by Rss12333** [yurtemre7/mouse-battery#1]
Exception in thread Thread-1 (get_battery):
Traceback (most recent call last):
  File "C:\Users\ras24\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner
    self.run()
  File "C:\Users\ras24\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\ras24\Downloads\mouse-battery-master\mouse-battery-master\mouse.py", line 35, in get_battery
    icon.icon = create_battery_icon()
                ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ras24\Downloads\mouse-battery-master\mouse-battery-master\mouse.py", line 64, in create_battery_icon
    draw.rectangle((0, 100, 100, 100 - battery_level), fill="green")
  File "C:\Users\ras24\AppData\Local\Programs\Python\Python311\Lib\site-packages\PIL\ImageDraw.py", line 292, in rectangle
    self.draw.draw_rectangle(xy, fill, 1)
ValueError: y1 must be greater than or equal to y0

I have a steelseries prime wireless. it shows up in the taskbar but doesn't show me the battery

**Comment by yurtemre7** [comment]
Hey, I think I fixed the problem! Please redownload everything, and try again!
The issue was that I used a slightly older version as your PC did, so I updated everything accordingly.

Hope it helped!

**Comment by Rss12333** [comment]
> Hey, I think I fixed the problem! Please redownload everything, and try again! The issue was that I used a slightly older version as your PC did, so I updated everything accordingly.
> 
> Hope it helped!

it works as intended now on the primed wireless, thank you :)
